// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPFxLe89Dl-44EwOC8moc5K1MQ_kTxapA',
    appId: '1:158178643894:web:50e00297e3e5ba53b43b17',
    messagingSenderId: '158178643894',
    projectId: 'grocery-go-backend',
    authDomain: 'grocery-go-backend.firebaseapp.com',
    databaseURL: 'https://grocery-go-backend-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-go-backend.firebasestorage.app',
    measurementId: 'G-FMT5HMC8R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqFRWYkxme7Q0U_l3nn1pAKIG76zrTxU',
    appId: '1:158178643894:android:59774258b5a30633b43b17',
    messagingSenderId: '158178643894',
    projectId: 'grocery-go-backend',
    databaseURL: 'https://grocery-go-backend-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-go-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRBSH5ohwjpP1SoAuJzjE0Xx08ZLreYM',
    appId: '1:158178643894:ios:fb8e312bfc208c94b43b17',
    messagingSenderId: '158178643894',
    projectId: 'grocery-go-backend',
    databaseURL: 'https://grocery-go-backend-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-go-backend.firebasestorage.app',
    iosBundleId: 'com.example.groceryGoShopper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGRBSH5ohwjpP1SoAuJzjE0Xx08ZLreYM',
    appId: '1:158178643894:ios:fb8e312bfc208c94b43b17',
    messagingSenderId: '158178643894',
    projectId: 'grocery-go-backend',
    databaseURL: 'https://grocery-go-backend-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-go-backend.firebasestorage.app',
    iosBundleId: 'com.example.groceryGoShopper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPFxLe89Dl-44EwOC8moc5K1MQ_kTxapA',
    appId: '1:158178643894:web:9cd3797dc07ccf76b43b17',
    messagingSenderId: '158178643894',
    projectId: 'grocery-go-backend',
    authDomain: 'grocery-go-backend.firebaseapp.com',
    databaseURL: 'https://grocery-go-backend-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-go-backend.firebasestorage.app',
    measurementId: 'G-WBBPFSGD88',
  );
}
